version: '3.1'

services:
  web:
    image: localgyros/php-composer
    environment:
      user: "${UID}:${GID}"
      # NB: the default for PHP_OPCACHE_VALIDATE_TIMESTAMPS is 0, which may be what you
      # want for production, but for dev you certainly want file changes to be detected, thus set to 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      HOME: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - lvf_scratch_data:/var/lib/postgresql/data
    command: php artisan serve

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lvf_scratch_db

volumes:
  lvf_scratch_data: